# -*- coding: utf-8 -*-
"""Ollama Big FineTUne.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15lotYPJgUtxiMQxPKGS7DFWRIgjiO0ft
"""

!pip install unsloth accelerate bitsandbytes datasets trl

import argparse
import json
import torch
from datasets import load_dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainingArguments,
    Trainer,
)
from peft import LoraConfig, get_peft_model

from huggingface_hub import login
login()

def tokenize(example, tokenizer, max_len=256):
    text = example["prompt"] + example["completion"]
    tokens = tokenizer(
        text,
        truncation=True,
        padding="max_length",
        max_length=max_len,
    )
    tokens["labels"] = tokens["input_ids"].copy()
    return tokens

def main(args):
    model_name = "meta-llama/Llama-3.2-1B-Instruct"

    print(f"[INFO] Training oracle for dataset: {args.dataset}")

    tokenizer = AutoTokenizer.from_pretrained(
        model_name,
        use_fast=True,
    )
    tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype=torch.float16,
        device_map="auto",
    )

    lora_cfg = LoraConfig(
        r=8,
        lora_alpha=16,
        target_modules=["q_proj", "v_proj"],
        lora_dropout=0.05,
        bias="none",
        task_type="CAUSAL_LM",
    )

    model = get_peft_model(model, lora_cfg)
    model.print_trainable_parameters()

    dataset = load_dataset(
        "json",
        data_files=args.dataset,
        split="train",
    )

    dataset = dataset.map(
        lambda ex: tokenize(ex, tokenizer),
        remove_columns=dataset.column_names,
    )

    training_args = TrainingArguments(
        output_dir=args.output,
        per_device_train_batch_size=8,
        gradient_accumulation_steps=2,
        learning_rate=2e-4,
        num_train_epochs=3,
        fp16=True,
        logging_steps=100,
        save_strategy="epoch",
        save_total_limit=1,
        report_to="none",
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=dataset,
        tokenizer=tokenizer,
    )

    trainer.train()

    print("[INFO] Saving LoRA adapter...")
    model.save_pretrained(args.output)
    tokenizer.save_pretrained(args.output)

if __name__ == "__main__":
    import sys
    parser = argparse.ArgumentParser()

    parser.add_argument("--dataset", default="datasets/L6_more_0_than_1.jsonl")
    parser.add_argument("--output", default="outputs/L6_more_0_than_1")

    args, _ = parser.parse_known_args()
    main(args)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile merge_lora.py
# import torch
# from transformers import AutoModelForCausalLM, AutoTokenizer
# from peft import PeftModel
# 
# BASE_MODEL = "meta-llama/Llama-3.2-1B-Instruct"
# LORA_PATH = "outputs/L6_more_0_than_1"
# OUT_PATH  = "outputs/L6_more_0_than_1_merged"
# 
# model = AutoModelForCausalLM.from_pretrained(
#     BASE_MODEL,
#     torch_dtype=torch.float16,
#     device_map="auto",
# )
# 
# model = PeftModel.from_pretrained(model, LORA_PATH)
# model = model.merge_and_unload()
# 
# tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)
# 
# model.save_pretrained(OUT_PATH, safe_serialization=True)
# tokenizer.save_pretrained(OUT_PATH)
# 
# print("LoRA merged and full model saved")

!python merge_lora.py

# !git clone https://github.com/ggerganov/llama.cpp

!python llama.cpp/convert_hf_to_gguf.py \
  outputs/L6_more_0_than_1_merged \
  --outfile lstarL6-f16.gguf \
  --outtype f16

!./llama.cpp/llama-quantize \
  lstar-f16.gguf \
  lstar.gguf \
  q4_k_m

!ls llama.cpp/

# Commented out IPython magic to ensure Python compatibility.
# %cd content/llama.cpp/

# Commented out IPython magic to ensure Python compatibility.
!mkdir -p build
# %cd build

!cmake ..

!cmake --build . --target llama-quantize

# Commented out IPython magic to ensure Python compatibility.
# %cd content/
!./llama.cpp/build/llama-quantize \
  lstar-f16.gguf \
  lstar.gguf \
  q4_k_m

!find llama.cpp -name "llama-quantize"

!./llama.cpp/build/bin/llama-quantize \
  lstarL6-f16.gguf \
  lstarL6.gguf \
  q4_k_m

